# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('FOAF', 'FOAF'), ('FRIENDS', 'FRIENDS'), ('SERVERONLY', 'SERVERONLY')], default='PUBLIC', max_length=20),
        ),
    ]
